on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["arm64", amd64]
    steps:
    - name: Show environment
      run: export
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@feature/build-phase
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_command: "make all"
        binary_name: "helm-values"
        extra_files: LICENSE README.md
